add dummy manifest file usage for the flatpak workflow

diff --git a/.github/workflows/build-linux.yml b/.github/workflows/build-linux.yml
--- a/.github/workflows/build-linux.yml
+++ b/.github/workflows/build-linux.yml
@@ -40,36 +40,36 @@ jobs:
         run: npx electron-builder --linux --x64 --dir
         working-directory: simpliplay
         
-      - name: Patch package.json
-        run: |
-          # save OG package json
-          cp simpliplay/package.json simpliplay/package.json.orig
-          # Check if jq is installed; if not, install it
-          if ! command -v jq &> /dev/null
-          then
-            echo "jq not found, installing..."
-            sudo apt-get update
-            sudo apt-get install -y jq
-          fi
+      # - name: Patch package.json
+      #   run: |
+      #     # save OG package json
+      #     cp simpliplay/package.json simpliplay/package.json.orig
+      #     # Check if jq is installed; if not, install it
+      #     if ! command -v jq &> /dev/null
+      #     then
+      #       echo "jq not found, installing..."
+      #       sudo apt-get update
+      #       sudo apt-get install -y jq
+      #     fi
 
-          # patch the json to use select electron for compat
-          jq '.devDependencies.electron="40.0.0" | .devDependencies["electron-builder"]="26.0.1"' \
-              simpliplay/package.json.orig > simpliplay/package.flatpak.json
+      #     # patch the json to use select electron for compat
+      #     jq '.devDependencies.electron="40.0.0" | .devDependencies["electron-builder"]="26.0.1"' \
+      #         simpliplay/package.json.orig > simpliplay/package.flatpak.json
               
-          # print the json to double check if jq actually worked...
-          echo "electron $(jq -r '.devDependencies.electron' simpliplay/package.flatpak.json)"
-          echo "electron-builder $(jq -r '.devDependencies["electron-builder"]' simpliplay/package.flatpak.json)"
+      #     # print the json to double check if jq actually worked...
+      #     echo "electron $(jq -r '.devDependencies.electron' simpliplay/package.flatpak.json)"
+      #     echo "electron-builder $(jq -r '.devDependencies["electron-builder"]' simpliplay/package.flatpak.json)"
           
-          # replace package.json for flatpak build
-          mv simpliplay/package.flatpak.json simpliplay/package.json
+      #     # replace package.json for flatpak build
+      #     mv simpliplay/package.flatpak.json simpliplay/package.json
 
       - name: Build Flatpak
         run: npx electron-builder --linux flatpak --x64
         working-directory: simpliplay
         continue-on-error: true
 
-      - name: Restore package.json
-        run: mv simpliplay/package.json.orig simpliplay/package.json # redundant for now but might be useful in future
+      # - name: Restore package.json
+      #   run: mv simpliplay/package.json.orig simpliplay/package.json # redundant for now but might be useful in future
 
       - uses: actions/upload-artifact@v6
         with:
@@ -120,7 +120,7 @@ jobs:
       - name: Install GNOME packages
         run: sudo snap install gnome-3-28-1804
 
-      - name: Install GTK theme stuff
+      - name: Install GTK theme snap
         run: sudo snap install gtk-common-themes
 
       - name: Install core22 snap
@@ -136,28 +136,28 @@ jobs:
           sudo apt-get install -y build-essential flatpak flatpak-builder
         continue-on-error: true
 
-      - name: Patch package.json for Flatpak
-        run: |
-          # Save og
-          cp simpliplay/package.json simpliplay/package.json.orig
-          # Check if jq is installed; if not, install it
-          if ! command -v jq &> /dev/null
-          then
-            echo "jq not found, installing..."
-            sudo apt-get update
-            sudo apt-get install -y jq
-          fi
-          # patch the json to use select electron and electron-builder for compat
-          jq '.devDependencies.electron="40.0.0" | .devDependencies["electron-builder"]="26.0.1"' \
-              simpliplay/package.json.orig > simpliplay/package.flatpak.json
+      # - name: Patch package.json for Flatpak
+      #   run: |
+      #     # Save og
+      #     cp simpliplay/package.json simpliplay/package.json.orig
+      #     # Check if jq is installed; if not, install it
+      #     if ! command -v jq &> /dev/null
+      #     then
+      #       echo "jq not found, installing..."
+      #       sudo apt-get update
+      #       sudo apt-get install -y jq
+      #     fi
+      #     # patch the json to use select electron and electron-builder for compat
+      #     jq '.devDependencies.electron="41.0.4" | .devDependencies["electron-builder"]="26.0.1"' \
+      #         simpliplay/package.json.orig > simpliplay/package.flatpak.json
               
-          # print the json to double check if jq actually worked...
-          echo "electron $(jq -r '.devDependencies.electron' simpliplay/package.flatpak.json)"
-          echo "electron-builder $(jq -r '.devDependencies["electron-builder"]' simpliplay/package.flatpak.json)"
+      #     # print the json to double check if jq actually worked...
+      #     echo "electron $(jq -r '.devDependencies.electron' simpliplay/package.flatpak.json)"
+      #     echo "electron-builder $(jq -r '.devDependencies["electron-builder"]' simpliplay/package.flatpak.json)"
           
-          # replace package.json for flatpak build cuz electron-builder is unfortunately
-          # picky regarding flatpaks
-          mv simpliplay/package.flatpak.json simpliplay/package.json
+      #     # replace package.json for flatpak build cuz electron-builder is unfortunately
+      #     # picky regarding flatpaks
+      #     mv simpliplay/package.flatpak.json simpliplay/package.json
 
       - name: Create unpacked build for Flatpak
         run: npx electron-builder --linux --arm64 --dir
@@ -171,17 +171,20 @@ jobs:
           #if ! pwd | grep -q "simpliplay"; then
             #cd simpliplay
           #fi
-          if [ ! -d node_modules ]; then
-            echo "node_modules wasn't found, will install deps now"
-            npm install
-          fi
-          npx electron-builder --linux flatpak --arm64
+          # if [ ! -d node_modules ]; then
+          #   echo "node_modules wasn't found, will install deps now"
+          #   npm install
+          # fi
           
+          #TODO: actually make the manifest file
+          flatpak-builder --user --disable-rofiles-fuse --force-clean build-dir flatpak/to-be-made.yaml
+          flatpak build-export repo build-dir
+          flatpak build-bundle repo simpliplay.flatpak me.anirudhsevugan.SimpliPlay
         working-directory: simpliplay
         continue-on-error: true
 
-      - name: Restore package.json
-        run: mv simpliplay/package.json.orig simpliplay/package.json
+      # - name: Restore package.json
+      #   run: mv simpliplay/package.json.orig simpliplay/package.json
 
       - uses: actions/upload-artifact@v6
         with:
@@ -208,7 +211,7 @@ jobs:
         with:
           node-version: 22
 
-      - name: Prepare i386 package.json
+      - name: Prepare package.json
         run: |
           # save og package.json
           cp simpliplay/package.json simpliplay/package.json.orig
@@ -230,7 +233,7 @@ jobs:
       - run: npm install
         working-directory: simpliplay
   
-      - name: Build AppImage i386
+      - name: Build AppImage
         run: npx electron-builder --linux AppImage --ia32
         working-directory: simpliplay
   
@@ -248,10 +251,12 @@ jobs:
         with:
           node-version: 22
 
-      #TODO: remove qemu emulation step cuz
-      #apparently snapcraft v8 has better platforms handling
+      # TODO: check if armv7 builds will work without qemu
+      # they don't always work with snapcraft
+      # in snapcraft v8 the --build-for flag helps
+      # but electron-builder does its own thing really
 
-      - name: Install QEMU for ARMv7 emulation
+      - name: Install QEMU for emulation
         run: |
           sudo apt-get update
           sudo apt-get install -y qemu-user-static binfmt-support
@@ -262,11 +267,11 @@ jobs:
         run: npm install
         working-directory: simpliplay
 
-      - name: Build ARMv7 AppImage
+      - name: Build AppImage
         run: npx electron-builder --linux AppImage --armv7l
         working-directory: simpliplay
   
-      - name: Upload ARMv7 AppImage
+      - name: Upload AppImage
         uses: actions/upload-artifact@v6
         with:
            name: linux-armv7-appimage
