add flatpak build step and patching for armv7
since freedesktop runtime dropped support for armv7 after the 19.08 runtime patching can be used to downgrade it, and the electron baseapp still supports it; dunno how it will work with super new electron versions though

diff --git a/.github/workflows/build-linux.yml b/.github/workflows/build-linux.yml
--- a/.github/workflows/build-linux.yml
+++ b/.github/workflows/build-linux.yml
@@ -197,47 +197,6 @@ jobs:
         with:
           name: linux-arm64-flatpak
           path: simpliplay/dist/*.flatpak
-        continue-on-error: true
-
-  build_i386:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v6
-  
-      - uses: actions/setup-node@v6
-        with:
-          node-version: 22
-
-      - name: Prepare package.json
-        run: |
-          # save og package.json
-          cp simpliplay/package.json simpliplay/package.json.orig
-      
-          # is jq installed?
-          if ! command -v jq &> /dev/null
-          then
-            echo "jq not found, installing..."
-            sudo apt-get update
-            sudo apt-get install -y jq
-          fi
-      
-          # patch package.json to use Electron v3.1
-          jq '.devDependencies.electron="3.1.13"' simpliplay/package.json.orig > simpliplay/package.i386.json
-      
-          # replace package.json for the i386 build
-          mv simpliplay/package.i386.json simpliplay/package.json
-  
-      - run: npm install
-        working-directory: simpliplay
-  
-      - name: Build AppImage
-        run: npx electron-builder --linux AppImage --ia32
-        working-directory: simpliplay
-  
-      - uses: actions/upload-artifact@v6
-        with:
-          name: linux-i386-appimage
-          path: simpliplay/dist/*.AppImage
 
   build_armv7:
     runs-on: ubuntu-22.04-arm
@@ -267,12 +226,6 @@ jobs:
       - name: Build AppImage
         run: npx electron-builder --linux AppImage --armv7l
         working-directory: simpliplay
-  
-      - name: Upload AppImage
-        uses: actions/upload-artifact@v6
-        with:
-           name: linux-armv7-appimage
-           path: simpliplay/dist/*.AppImage
 
       # the below is to prevent snapcraft from crashing
       # for some reason it does not cope without these deps
@@ -296,11 +249,90 @@ jobs:
       - name: Build snap
         run: npx electron-builder --linux snap --armv7l
         working-directory: simpliplay
+
+      - name: Install Flatpak libs
+        run: |
+          sudo apt-get update
+          # build-essential will be useful if I ever add native c++ modules
+          # but otherwise it won't do much
+          sudo apt-get install -y build-essential flatpak flatpak-builder
+        #continue-on-error: true
+
+      # the patch below's needed cuz freedesktop runtime dropped
+      # support for armv7 after the 19.08 runtime
+      # but the electron baseapp and older freedesktop runtime
+      # both still have versions for it so patching should work fine
+      - name: Patch manifest
+        run: sed -i "s/'25.08'/'19.08'/g" flatpak/me.anirudhsevugan.SimpliPlay.yml # sed is so annoying sometimes
+        
+      - name: Build Flatpak
+        run: |
+          # setup flathub repo
+          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
+          # now build
+          flatpak-builder --user --install-deps-from=flathub --force-clean build-dir flatpak/me.anirudhsevugan.SimpliPlay.yml
+          flatpak build-export repo build-dir
+          flatpak build-bundle repo SimpliPlay-armv7-linux.flatpak me.anirudhsevugan.SimpliPlay
+          mv *.flatpak dist/
+        working-directory: simpliplay
         
       - uses: actions/upload-artifact@v6
         with:
           name: linux-armv7l-v2-snap
           path: simpliplay/dist/*.snap
+
+      - uses: actions/upload-artifact@v6
+        with:
+           name: linux-armv7-appimage
+           path: simpliplay/dist/*.AppImage
+
+      - uses: actions/upload-artifact@v6
+        with:
+           name: linux-armv7-flatpak
+           path: simpliplay/dist/*.flatpak
+
+  build_unstable_i386:
+    runs-on: ubuntu-slim
+    steps:
+      - uses: actions/checkout@v6
+  
+      - uses: actions/setup-node@v6
+        with:
+          node-version: 22
+
+      - name: Patch package.json
+        run: |
+          # save og package.json
+          cp simpliplay/package.json simpliplay/package.json.orig
+      
+          # is jq installed?
+          if ! command -v jq &> /dev/null
+          then
+            echo "jq not found, installing..."
+            sudo apt-get update
+            sudo apt-get install -y jq
+          fi
+      
+          # patch package.json to use Electron v3.1
+          # might be useful for debugging or checking on i386
+          # but the app uses functions that might be too new for electron v3
+          # crashes on electron2 but haven't tested v3 properly yet
+          jq '.devDependencies.electron="3.1.13"' simpliplay/package.json.orig > simpliplay/package.i386.json
+      
+          # replace package.json for the i386 build
+          mv simpliplay/package.i386.json simpliplay/package.json
+  
+      - run: npm install
+        working-directory: simpliplay
+  
+      - name: Build AppImage
+        run: npx electron-builder --linux AppImage --ia32
+        working-directory: simpliplay
+  
+      - uses: actions/upload-artifact@v6
+        with:
+          name: linux-unstable-i386-appimage
+          path: simpliplay/dist/*.AppImage
 
   # start-linux-tests:
   #   name: Start Linux Tests
