Update build-macos.yml

diff --git a/.github/workflows/build-macos.yml b/.github/workflows/build-macos.yml
--- a/.github/workflows/build-macos.yml
+++ b/.github/workflows/build-macos.yml
@@ -29,6 +29,25 @@ jobs:
           security list-keychains -s build.keychain login.keychain-db
           security unlock-keychain -p "" build.keychain
 
+      - name: Check secret presence
+        env:
+          CERT_P12_BASE64: ${{ secrets.MAC_CERTIFICATE_P12 }}
+          CERT_PASSWORD: "${{ secrets.MAC_CERTIFICATE_PASSWORD }}"
+        run: |
+          if [ -z "$CERT_PASSWORD" ]; then
+            echo "Password secret is empty or missing!"
+            exit 1
+          else
+            echo "Password is set"
+          fi
+
+          if [ -z "$CERT_P12_BASE64" ]; then
+            echo "P12 secret is empty or missing!"
+            exit 1
+          else
+            echo "P12 is set"
+          fi
+
       - name: Import macOS certificate
         env:
           CERT_P12_BASE64: ${{ secrets.MAC_CERTIFICATE_P12 }}
