Update upload_snap.yml

diff --git a/.github/workflows/upload_snap.yml b/.github/workflows/upload_snap.yml
--- a/.github/workflows/upload_snap.yml
+++ b/.github/workflows/upload_snap.yml
@@ -6,6 +6,7 @@ on:
 jobs:
   publish:
     runs-on: ubuntu-latest
+    environment: snap-upload # no environment = builds fail you can kinda see why when you glance at this yml enough
     steps:
       - name: Download artifacts for all arches
         uses: actions/download-artifact@v4
@@ -13,7 +14,7 @@ jobs:
           # matches all the snap artifacts
           pattern: "*-snap"
           merge-multiple: true
-          # this MUST be changed if artifact names are changed to not include "-snap"
+          # this MUST be changed if artifact names are changed to not include "-snap" so dont forget!!!!!!!
 
       - name: Install snapcraft CLI
         run: sudo snap install snapcraft --classic
@@ -23,7 +24,7 @@ jobs:
           SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
         run: |
           # verify credentials
-          snapcraft whoami || (echo "Credentials have expired! To renew, run 'snapcraft export-login --snaps simpliplay --expires $(date -v+1y +%Y-%m-%d) snapcraft.login' and update any necessary secrets" && exit 1)
+          snapcraft whoami || (echo "Credentials have expired! To renew, run 'SNAPCRAFT_STORE_AUTH=candid snapcraft export-login --snaps simpliplay --expires $(date -v+1y +%Y-%m-%d) snapcraft.login' and update any necessary secrets" && exit 1)
 
           # get all the snaps and upload to stable!!!
           for snap_file in *.snap; do
